name: CI:clippy+rustfmt

on:
  pull_request:
  push:
    branches:
      - main

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        components: rustfmt, clippy

    - name: Run rust clippy
      run: |
        cargo +nightly clippy --all-targets --all-features

    - name: Run rust fmt
      run: |
        cargo +nightly fmt --check
